- python/xoscar/profiling.py
- python/xoscar/tests/test_profiling.py
> ENH: remove subtask in profiling

- python/xoscar/backends/core.py
- python/xoscar/backends/message.pyx
- python/xoscar/profiling.py
> ENH: do not use global variable for profiling

- python/xoscar/tests/test_utils.py
- python/xoscar/utils.py
> TST: add tests for utils

- python/xoscar/backends/communication/socket.py
- python/xoscar/constants.py
Use /tmp/xoscar as default temp dir
> ENH: use /tmp/xoscar as default temp dir

- python/xoscar/constants.py
> BUG: Fix os error on MacOS

- python/xoscar/backends/indigen/backend.py
- python/xoscar/backends/test/backend.py
The code about `n_io_process` will be moved into Xorbits in https://github.com/xprobe-inc/xorbits/pull/401, remove code in Xoscar.
Fixes #xxxx
> CLN: Remove `n_io_process`

- doc/source/conf.py
Remove the unused matplotlib extension from extension list.
> BLD: fix readthedocs

- doc/source/getting_started/index.rst
- doc/source/getting_started/llm-inference.rst
Add a tutorial that do LLM inference with Xoscar on both CPU and GPU.
> DOC: LLM inference

- .pre-commit-config.yaml
- python/xoscar/api.py
- python/xoscar/backends/context.py
- python/xoscar/backends/message.pyi
- python/xoscar/backends/message.pyx
- python/xoscar/backends/pool.py
- python/xoscar/backends/test/tests/test_transfer.py
- python/xoscar/context.pyx
- python/xoscar/core.pxd
- python/xoscar/core.pyx
> ENH: copy_to supports aio files

- .github/workflows/python.yaml
> CHORE: Restrict fork repositories from using ci resources

- python/xoscar/backends/indigen/pool.py
- python/xoscar/backends/pool.py
For some versions of Python, it raises RuntimeError: cannot schedule new futures after shutdown, use "cannot schedule new futures " to match error message.
Fixes #xxxx
> BUG: Modify match words for catching error message

- python/xoscar/__init__.py
> BUG: cannot import file_object_ref from xoscar directly

- python/xoscar/backends/communication/utils.py
When I adapt ``copy_to`` to ``xorbits``, xoscar cannot deserialize the transferred cupy object. 
In xorbits, all the cuda object will use ``rmm.DeviceBuffer``-based object to store actual data. 
But in xoscar, the result of deserialization could be the organic ``bytes`` object.
I think using ``rmm.DeviceBuffer`` is definitely correct.
> BUG: The bytes returned by cuda StreamReader may leads to deserialization failed

- .github/workflows/build-wheel.yaml
- README.md
- doc/source/conf.py
- doc/source/index.rst
- python/setup.cfg
> CHORE: Fix repo name

- python/xoscar/_utils.pyx
Shared python environments that contain cuda-related environments but do not actually have GPU environments on the machine only show warnings.
Fixes https://github.com/xorbitsai/xorbits/issues/595
> BUG: disable import cuda error when cpu only in a shared python env

- python/xoscar/_utils.pyx
Reverts xorbitsai/xoscar#47
Here' a big issue due to this PR:
When the use's env has some problem (for example, python env has cupy and cudf, while the machine is a cpu machine), this pr will leads to some unexpected problems. Because in this case ``cudf is not None`` is ``True``, but when user uses ``cudf.xxx``, problems would happen.
Will fix this in another PR.
> Revert "BUG: disable import cuda error when cpu only in a shared python env"

- python/xoscar/backends/communication/ucx.py
- python/xoscar/collective/__init__.py
- python/xoscar/collective/common.py
- python/xoscar/collective/core.py
- python/xoscar/collective/process_group.py
- python/xoscar/collective/tests/test_core.py
- python/xoscar/collective/utils.py
- python/xoscar/utils.py
Related #22
Tested on xorbits. 
In the case of worker number 5 for tpch 100, ``broadcast`` is much more slower than ``copy_to``.
Maybe when cluster scale is very large, collective communication may speed up. But I do not know now.
See issue: https://stackoverflow.com/questions/26558189/mpi-broadcast-very-slow
> FEAT: Impl collective communication interface

- .github/workflows/build-wheel.yaml
- python/setup.py
Here is the build-wheel test link : https://github.com/YibinLiu666/lybtest/actions/runs/5735869475 
Fixes #xxxx
> CHORE:add msbuild to build wheel

- python/xoscar/__init__.py
- python/xoscar/batch.py
- python/xoscar/core.pyx
- python/xoscar/tests/test_batch.py
> ENH: add no_lock for avoiding possible dead lock during local actor ref method call

- python/xoscar/constants.py
Following the discussion on my question on the slack channel, this PR adds the ability to set an environment variable for the xoscar temp directory. I've just called it `XOSCAR_DIR` for now. If the variable is not set the old behaviour of using the home directory is maintened.
> ENH: Environment variable to set the Xoscar temp directory.

- python/xoscar/backends/test/tests/test_transfer.py
> TST: np.random.bytes with input float issue

- .github/workflows/build-wheel.yaml
- CMakeLists.txt
- cpp/CMakeLists.txt
- python/xoscar/collective/common.py
- python/xoscar/collective/core.py
- python/xoscar/collective/process_group.py
- python/xoscar/collective/utils.py
> BUG: Fix import error on Mac

- python/pyproject.toml
Test passed: https://github.com/ChengjieLi28/xoscar/actions/runs/6068932033
Fixes #xxxx
> CHORE: Remove win32 support

- python/xoscar/core.pyx
- python/xoscar/tests/test_batch.py
> BUG: Fix no_lock not work

- .github/workflows/python.yaml
- python/xoscar/serialization/core.pyx
- python/xoscar/serialization/pyfury.py
- python/xoscar/serialization/tests/test_serial.py
> FEAT: Support fury

- python/xoscar/backends/pool.py
> ENH: Copy sub_processes in monitor_sub_pools

- python/xoscar/__init__.py
- python/xoscar/api.py
- python/xoscar/tests/test_generator.py
Generators can not be transferred directly between actors, users must wrap it to a iterator object referencing to the code of xinference ModelActor.
But the wrapping codes are complex and need to rewrite them in every generators.
This PR provides a decorator: xo.generator, users can define generators as usual in a simple way:
```
import asyncio
import time
import xoscar as xo
address = "127.0.0.1:8000"
class WorkerActor(xo.StatelessActor):
@xo.generator
def chat(self):
for x in "hello oscar by sync":
yield x
time.sleep(0.1)
@xo.generator
async def achat(self):
for x in "hello oscar by async":
yield x
await asyncio.sleep(0.1)
@classmethod
def uid(cls):
return "worker"
class SupervisorActor(xo.StatelessActor):
@xo.generator
async def chat(self):
worker_actor: xo.ActorRef["WorkerActor"] = …
```
> FEAT: make it easy to define generator methods in Actor

- python/xoscar/api.py
- python/xoscar/core.pyx
- python/xoscar/tests/test_generator.py
- If a normal function is decorated by `xo.generator`, then the function will be run by `to_threads`.
- Regardless of whether a function is decorated by `xo.generator` returns a generator or an async generator or a value, the function should works as expected.
Fixes #xxxx
> FEAT: generator support normal function

- python/xoscar/api.py
- python/xoscar/tests/test_generator.py
`super().__getstate__` is not availabe for Python < 3.11
Fixes #xxxx
> BUG: Fix getstate compatibility

- python/xoscar/backends/context.py
- python/xoscar/tests/test_utils.py
- python/xoscar/utils.py
Senario:
server(supervisor) listen on 0.0.0.0, might because it has multiple ip address, or the server hide behind L4 loadbalancer.
client (worker) connect server from another host (by ip or hostname) will cause such error.
```
File "/root/inference/xinference/deploy/worker.py", line 65, in _start_worker                                                                                                                              
await start_worker_components(                                                                                                                                                                                 
File "/root/inference/xinference/deploy/worker.py", line 43, in start_worker_components …
```
> ENH: fix non-local client connection problem when server listen on 0.0.0.0

- python/xoscar/backends/core.py
In xinference, interrupting a request to the model will trigger asyncio.exceptions InvalidStateError: invalid state。
> fix: invalid state

- .github/workflows/build-wheel.yaml
macos-latest now default uses arm64 rather than x86_64.  See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Tested on my repo:
https://github.com/luweizheng/xoscar/actions/runs/9876596547/
> BLD: Fix macos build error

- .github/mergify.yml
- .github/workflows/build-wheel.yaml
- .github/workflows/python.yaml
`macos-latest` runner updates Xcode: https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
workaround: use `macos-13`.
> BLD: Fix macos build

- python/xoscar/backends/indigen/pool.py
This fix bug of xinference:
Only the main process got kill, but subprocess leaves behind
before terminate-model:
root      179070 1942  1.3 60529056 7144300 ?    Rl   04:22   9:23              \_ Model: qwen2-instruct:72-0-1722111769.2038095
root      179297 2395  1.3 59784688 6867800 ?    Rl   04:22   9:34              |   \_ Model: qwen2-instruct:72-0-1722111769.2038095
root      179300 2373  1.3 59784740 6881352 ?    Rl   04:22   9:29              |   \_ Model: qwen2-instruct:72-0-1722111769.2038095
root      179301 2362  1.2 59747064 6858788 ?    Rl   04:22   9:26              |   \_ Model: qwen2-instruct:72-0-1722111769.2038095
after terminate-model:
root      179297 2395  1.3 59784688 6867800 ?    Rl   04:22   9:34              \_ Model: qwen2-instruct:72-0-1722111769.2038095
root …
> Fix: remove_sub_pool should kill subprocess gracefully

- .github/workflows/python.yaml
- python/xoscar/backends/communication/socket.py
- python/xoscar/backends/communication/ucx.py
- python/xoscar/backends/indigen/pool.py
- python/xoscar/backends/indigen/tests/test_pool.py
- python/xoscar/collective/core.py
- python/xoscar/tests/test_utils.py
- python/xoscar/utils.py
create_actor_pool: Add extra_conf option listen_elastic_ip
Usage:
```
create_actor_pool(elastic_address,
n_process=0,
extra_conf={'listen_elastic_ip': True},
)
```
While xinference worker serve on cloud elastic_ip,
the address used in create_actor_pool() and create_actor both have to be the elastic ip,
in order for ActorRef passing around RPC method to client, but we could only listen on 0.0.0.0.
(Because the ip is not only valid outside the host)
Additional fixes:
1. The previous PR #92  does not consider ucx address format:  `ucx://127:0.0.1:3456`
2. Fix some address.split() for ipv6 case because ipv6 contains multiple `:` in the ip part
Add cross unittests for ipv6 X listen_elastic_ip X ucx.
The only missing part is ucx X ipv6, because ucx does not supoort ipv6 
ISSUE: …
> Enable create_actor_pool to use elastic ip

- .github/workflows/python.yaml
- python/xoscar/backends/communication/socket.py
- python/xoscar/backends/indigen/tests/test_pool.py
In the last [PR](https://github.com/xorbitsai/xoscar/pull/95), we added a `parse_config` method in socket channel. This method is mainly for extracting `listen_elastic_ip` in `extra_conf`. 
However, when xorbits calls it, this `config` contains keyword arguments like `ucx` in `extra_conf`.
The config will further affect the following code as `asyncio.start_server` does not have the `ucx` keyword argument.
```python
aio_server = await asyncio.start_server(
handle_connection, host=_host, port=port, **config
)
```
In xorbits, this config contains stuff about ucx like: `{'ucx': {'tcp': None, 'nvlink': None, 'infiniband': None, 'rdmacm': None, 'cuda-copy': None, 'create-cuda-contex': None}}`. This config is from `python/xorbits/_mars/deploy/oscar/base_config.yml`.
However, SocketChannel does …
> ENH: Fix socket channel config bug

- python/xoscar/backends/pool.py
- python/xoscar/utils.py
Fix route problem when both service listening 0.0.0.0:port calling each other
Two service listen on 0.0.0.0:1234, on different hosts:
xoscar.actor_ref(111.111.111.111:1234) will return unexpected LocalActorRef.
log print in context.actor_ref(111.111.111.111:1234)
``` 
actor_ref ActorRef(uid=b'supervisor', address='111.111.111.111:1234')
_call 111.111.111.111:1234
get client 111.111.111.111:1234
got LocalActorRef(uid=None, address='0.0.0.0:1234'), actor_weakref=<weakref at 0x75745bcdecf0; to 'CloudSupervisorActor' at 0x75745d3ed260>
fix_all_zero_ip()
got LocalActorRef(uid=None, address='111.111.111.111:1234'), actor_weakref=<weakref at 0x75745bcdecf0; to 'CloudSupervisorActor' at 0x75745d3ed260>
``` 
using the returned LocalActorRef, method call intend for remote service actually sent to …
> BUG: Fix route problem when listen on 0.0.0.0

- .github/workflows/python.yaml
- python/setup.cfg
update doc dependency: sphinx>=8.0.0
Using Sphinx 4.5.0 will fail when building xorbits's doc
Fixes #xxxx
> DOC: update sphinx to latest version

- .github/workflows/build-wheel.yaml
- .github/workflows/python.yaml
github runner `macos-13` auto `arch` is x86_64 this pr add arm64.
see: https://github.com/actions/runner-images/tree/main/images/macos
> BLD: macos arm64

- .github/workflows/python.yaml
- CI/conda-environment.yml
- CI/requirements-wheel.txt
- python/pyproject.toml
- python/setup.cfg
- python/xoscar/backends/communication/ucx.py
- python/xoscar/serialization/core.pyx
- unpin numpy < 2.0, remove old pandas code (< 1.1.0)
- move [ucx-py]() to [ucxx](https://github.com/rapidsai/ucxx/) as [ucxx](https://github.com/rapidsai/ucxx/) is the recommended package
> ENH: unpin "numpy<2.0" & move ucx-py to ucxx

- .github/workflows/python.yaml
- python/xoscar/utils.py
fix deprecation warning by pkgutil.find_loader
DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
> ENH: fix deprecation warning by pkgutil.find_loader

- python/xoscar/backends/core.py
- python/xoscar/backends/pool.py
- python/xoscar/serialization/aio.py
While server-side recv invalid format data, previously will not handle exception and leaving connection not close.
The exception situation including invalid header,  or deserialization fails
Fixes #110
None
> ENH: Refine connection exception handling

- python/xoscar/backends/communication/socket.py
- python/xoscar/backends/indigen/tests/test_pool.py
- python/xoscar/constants.py
asyncio default connection timeout is too long. we add CONNECT_TIMEOUT optional config default to 8 sec
> FEAT: Add CONNECT_TIMEOUT option

- .github/workflows/python.yaml
- python/xoscar/backends/communication/dummy.py
- python/xoscar/backends/communication/socket.py
- python/xoscar/backends/communication/ucx.py
- python/xoscar/backends/core.py
- python/xoscar/backends/test/tests/test_actor_context.py
Background: If an actor is called from a thread and the thread exits after the call, the client will leak in the actor caller, and the corresponding channel will still be open.
This PR auto close the actor callers and channels that belongs to the exited thread.
Fixes #xxxx
> BUG: Fix leaking clients in actor caller

- python/xoscar/backends/communication/dummy.py
- python/xoscar/backends/communication/socket.py
- python/xoscar/backends/core.py
> BUG: Fix closing error

- python/xoscar/backends/indigen/pool.py
Normally, env like `CUDA_VISIBLE_DEVICES` is set in sub pool, but some imports like codes may be called before it, this may cause weird situation.
In this PR, a new environment variable `XOSCAR_PRE_SET_ENV` is added, if set to 1, the environment will be set in main pool, to make sure sub pool will get right env before creating. **This env is disabled by default thus will not effect anything.**
We'd better use subprocess instead of multiprocessing to ensure the sub pool is based on a very clean process, or this solution is just a temp way.
Fixes #xxxx
> ENH: support setting env on main pool

- .github/workflows/python.yaml
- python/xoscar/_utils.pyx
- python/xoscar/backends/indigen/tests/test_proxy.py
- python/xoscar/virtualenv/uv.py
The https://github.com/xorbitsai/xoscar/pull/126 introduced a `proxy_address` variable in `create_actor_ref(args)`, while `create_actor_ref(args)` can accept different kinds of `args`.
This PR fixes an issue in the `create_actor_ref` function where a ValueError was raised when trying to create an actor with a class object as the first argument, i.e., `create_actor_ref(ActorCls, other_args, other_kw_args)`.
> BUG: Fix ValueError when creating actor with class object as first argument

- python/xoscar/utils.py
- python/xoscar/virtualenv/core.py
- python/xoscar/virtualenv/uv.py
This PR fixed `get_python_path`, only returns value when path exists.
And shown in https://github.com/xorbitsai/inference/issues/3390 , no clue when the wrapped exception will be inited, thus added *args and **kwargs to prevent from hiding real error.
Fixes #xxxx
> ENH: get_python_path() returns value when path exists

- python/xoscar/__init__.py
- python/xoscar/api.py
- python/xoscar/backends/indigen/tests/test_pool.py
`asyncio.wait_for()` on Xoscar actor call cannot work as expected, because when time out, the future will be cancelled, but an actor call will catch this error, and send a `CancelMessage` to the dest pool, if the `CancelMessage` cannot be processed correctly(e.g. the dest pool hangs), the time out will never happen.
Thus this PR added a new API so that no matter the `CancelMessage` delivered or not, the timeout will happen as expected.
Fixes #xxxx
> FEAT: added wait_for API

- python/xoscar/virtualenv/core.py
- python/xoscar/virtualenv/uv.py
For the virtualenv, if the system site packages has some lib, for instance torch==2.6, if the packages to install rely on torch, the uv will try to install torch no matter it's installed in system site packages or not, thus maybe torch==2.7 will be installed, this will cause many issues, e.g. torchvision in system site packages may be incompatible. Hence, this PR add some special syntax for packages, e.g. `#system_torch#` , and it will be replaced with real version installed in system site pacakges.
Fixes #xxxx
> FEAT: extended packages for virtualenv

- .github/workflows/python.yaml
- python/pyproject.toml
- python/xoscar/backends/indigen/pool.py
> ENH: specifying env when creating sub pool (before updating os.environ when sub pool created)

- .github/workflows/python.yaml
- python/xoscar/virtualenv/core.py
- python/xoscar/virtualenv/tests/test_uv.py
- python/xoscar/virtualenv/uv.py
SInce latest uv would ask clear or not for an env, and in XInference we basically just call `create_env` without checking in advance, thus we added option, by default ignore to make it compatible with old behavior.
Fixes #xxxx
> ENH: support exists_env and create_env(exists="error|ignore|clear")

- python/xoscar/virtualenv/core.py
- python/xoscar/virtualenv/platform.py
- python/xoscar/virtualenv/tests/test_core.py
- python/xoscar/virtualenv/tests/test_uv.py
- python/xoscar/virtualenv/utils.py
- python/xoscar/virtualenv/uv.py
Extended syntax includes:
```
torch==2.0 ; has_cuda
xformers ; cuda_version >= '12.0'
cpu-lib ; not has_cuda
npu-lib ; has_npu
gpu-toolkit ; cuda_arch >= 'sm_80'
special-driver ; has_cuda and sys_platform == 'linux'
win-tool ; has_cuda and sys_platform == 'win32'
```
Fixes #xxxx
> ENH: support extended requirements syntax for virtualenv packages

- python/xoscar/virtualenv/uv.py
当虚拟环境的包过滤后为空的时候会报错，修复该错误
Fixes #xxxx
> BUG: Ignore virtual environment installation when the filtered package list is empty.
