python/xoscar/__init__.py

BUG: reorder import for init_extension_entrypoints

---

python/xoscar/constants.py
python/xoscar/tests/test_utils.py
python/xoscar/utils.py

ENH: use tempfile.gettempdir() for temp dir

---

python/xoscar/metrics/api.py

ENH: Modify debug level

---

README.md

DOC: Build from source

---

python/pyproject.toml

ENH: fix versions of dependencies in toml

---

python/xoscar/backends/indigen/pool.py

Subpools created by append_subpool do not have correct logging config.
Fixes #xxxx

BUG: append subpool logging

---

.pre-commit-config.yaml
python/xoscar/backends/communication/dummy.py
python/xoscar/backends/indigen/pool.py
python/xoscar/backends/indigen/tests/test_pool.py
python/xoscar/backends/pool.py
python/xoscar/backends/test/pool.py
python/xoscar/backends/test/tests/test_transfer.py
python/xoscar/collective/common.py
python/xoscar/collective/tests/test_core.py
python/xoscar/tests/test_batch.py
python/xoscar/tests/test_generator.py

ENH: stop using daemon=True for subpool

---

.github/workflows/build-wheel.yaml

BLD: fix windows CI

---

.github/workflows/build-wheel.yaml

Test it on my forked repo: https://github.com/luweizheng/xoscar/actions/runs/9740847432

BLD: Fix build_wheel.yml

---

python/xoscar/backends/core.py

BUG: Fix crash when exiting the daemon thread

---

.github/workflows/build-wheel.yaml
.github/workflows/python.yaml
CI/test_functionality.py
python/setup.cfg

This PR includes several improvements to our GitHub Actions workflows:
1. Updates all GitHub Actions to their latest stable versions:
- actions/checkout: v3 -> v4
- docker/setup-qemu-action: v2 -> v3
- actions/upload-artifact: v3 -> v4
- actions/download-artifact: v3 -> v4
- microsoft/setup-msbuild: v2 -> v1.3.1
- conda-incubator/setup-miniconda: v3 -> v4
- pypa/gh-action-pypi-publish: v1.5.0 -> v1.8.11
2. Optimizes build matrix configuration:
- Adds platform-id for better build identification
- Updates Python version format
- Removes redundant configurations

BLD: Update GitHub Actions and Optimize Build Matrix

---

python/xoscar/serialization/mlx.py
python/xoscar/serialization/tests/test_serial.py

This PR added MLX array serializers.
Fixes #xxxx

FEAT: add mlx serializer

---

.github/workflows/python.yaml
python/xoscar/serialization/mlx.py
python/xoscar/serialization/tests/test_serial.py

BUG: fix mlx serializer

---

.github/workflows/build-wheel.yaml
CMakeLists.txt
python/setup.py

Fix upload pypi error
Fixes #xxxx

BUG: Fix upload pypi error

---

python/setup.cfg
python/xoscar/virtualenv/__init__.py
python/xoscar/virtualenv/core.py
python/xoscar/virtualenv/tests/__init__.py
python/xoscar/virtualenv/tests/test_uv.py
python/xoscar/virtualenv/uv.py

FEAT: add virtual env support

---

python/xoscar/virtualenv/uv.py

ENH: just using parent's pipe for uv process

---

.github/workflows/python.yaml
CI/test_functionality.py
python/pyproject.toml
python/setup.cfg
python/xoscar/backends/communication/dummy.py
python/xoscar/backends/indigen/__main__.py
python/xoscar/backends/indigen/fate_sharing.py
python/xoscar/backends/indigen/pool.py
python/xoscar/backends/indigen/shared_memory.py
python/xoscar/backends/indigen/tests/test_debug.py
python/xoscar/backends/indigen/tests/test_indigen_actor_context.py
python/xoscar/backends/indigen/tests/test_pool.py
python/xoscar/backends/indigen/tests/test_proxy.py
python/xoscar/backends/pool.py
python/xoscar/backends/test/pool.py
python/xoscar/backends/test/tests/test_actor_context.py
python/xoscar/backends/test/tests/test_transfer.py
python/xoscar/collective/tests/test_nccl.py
python/xoscar/virtualenv/core.py
python/xoscar/virtualenv/tests/test_uv.py
python/xoscar/virtualenv/uv.py

- Use asyncio.subprocess.Process instead of multiprocessing
- Migrate kernel fate sharing support from ray: https://github.com/ray-project/ray
- Add a thread to sub pool for checking ppid.
- Allow sub pool start in venv.
Fixes #xxxx

FEAT: Launch worker in venv

---

.github/workflows/build-wheel.yaml

BLD: Fix build test

---

.github/workflows/build-wheel.yaml
python/xoscar/backends/indigen/__main__.py
python/xoscar/backends/indigen/fate_sharing.py
python/xoscar/backends/indigen/pool.py
python/xoscar/backends/pool.py

BLD: Fix the check for ppid

---

python/xoscar/virtualenv/uv.py

ENH: support specifying uv path via environment variable

---

python/xoscar/backends/indigen/pool.py
python/xoscar/virtualenv/uv.py

ENH: more logs

---

python/xoscar/virtualenv/tests/test_utils.py
python/xoscar/virtualenv/tests/test_uv.py
python/xoscar/virtualenv/utils.py
python/xoscar/virtualenv/uv.py

ENH: [virtualenv] Support capturing log when installing packages

---

python/xoscar/backends/indigen/pool.py

ENH: Avoid infinite waiting in kill_sub_pool

---

python/xoscar/serialization/mlx.py

BUG: Fix random hang issue for sending mlx array

---

python/xoscar/collective/backend/__init__.py
python/xoscar/collective/backend/nccl_backend.py

BUG: fix nccl_backend code that is not distributed in release wheel
